### ISSUE TITLE
into_img_file_gz

### ISSUE THREAD

**Issue by nilgoyette** [Enet4/nifti-rs#30]
Any reason `into_img_file_gz` is so complicated? I feel it could be replaced by 

    pub fn into_img_file_gz(mut path: PathBuf) -> PathBuf {
        if is_gz_file(&path) {
            // Leave only the first extension (.hdr)
            let _ = path.set_extension("");
        }
        path.with_extension("img.gz")
    }

It's shorter and it can't panic anymore. Am I forgetting a special case?

**Comment by Enet4** [comment]
Oh uh.. I have no idea. That indeed looks better and appropriate.

**Comment by Enet4** [comment]
Solved in #31.
