### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nilgoyette** [Enet4/nifti-rs#4]
I've been using your library on Windows and Debian an everything works well except one test. `minimal_by_hdr_and_img_gz()` uses `resources/minimal2.hdr` which is a link to `minimal.hdr`. Of course, Windows doesn't support link so it's trying to read the link as if it was the actual header.

I hesitate to change it myself because I don't know why you choosed a link in the first place. It seems to me that this test would work as much using `resources/minimal.hdr` but you already have this test so you must be testing something else... Anyway, I can fix it if you can't test on windows.

**Comment by Enet4** [comment]
Thanks for reporting. You're right, I don't usually test on Windows, although I could every now and then. It seems that I might have to throw the idea that symlinks just work off the window (no pun intended).

Have you tried [this configuration tweak](https://fishingcatblog.wordpress.com/2016/06/01/symbolic-links-in-windows-git-and-atom/)? If that won't work, I guess we can just copy the header files.

**Comment by nilgoyette** [comment]
Yes, it's working. Since we need to do that only when we contribute/test, I guess you can leave it this way. Thank you.
