### ISSUE TITLE
Rethink some of the header's default attribute values

### ISSUE THREAD

**Issue by Enet4** [Enet4/nifti-rs#41]
This was discussed in #40, but I'm filing an issue so that this concern is not forgotten.

> - `pixdim` should be [1.0; 8] by default.
> - `srow_x` and other should have an "identity" default.
> - `sform_code` should be 1 by default IF it's really the normal way to encode the transformation. Maybe  `qform_code` is the way, I don't know,

I believe we're still undecided on what should be the defaults for `sform_code` and `qform_code`.

**Comment by nilgoyette** [comment]
My colleague @jchoude tells me that we should do:

- reading
  - Normal case: if **either** `sform_code` or `qform_code` is present (not 0), apply the requested one.
  - Special case: both are present. Standard says nothing about this case but most tools use `sform`
- writing: calculate and write the 2 transformations with `sform_code = 1` and `qform_code = 0`. We will have to wait for #22 to do it properly though.

This doesn't directly answer the question, but as I understand it, the default Header should be

- "identity" in both transformations
- `sform_code = 1` 
- `qform_code = 0`

**Comment by jchoude** [comment]
Just a minor correction, @nilgoyette , the `qform_code` should also be `1`. `0` means that it's not recorded.

**Comment by Enet4** [comment]
I believe this has been resolved in #56. As usual, this can be brought up again if something is worth rethinking.
