### ISSUE TITLE
Automatic extension

### ISSUE THREAD

**Issue by nilgoyette** [Enet4/nifti-rs#49]
One of my users complained that ".nii" wasn't appended to the filename he provided to my program. I understand that there's no obvious answer to this question, but I think that a lib called `nifti-rs` should probably save ".nii" files by default instead of directly using the filename provided without question. What do you think about that?

**Comment by Enet4** [comment]
To be honest, I feel that this is a user facing issue, although there are a few contrasting ideas. For a library function which receives a complete file path, changing it to conform to a .nii or .nii.gz extension without any feedback is less predictable from a programmer's perspective.
On the other hand, our writing API is still in a fairly brittle state, considering that it only works for writing ndarray volumes and attempts to identify the intended output format (e.g. Gzip) from the file name.

```rust
let filename = temporary_dir().join("clean_volume_165");
volume.write(filename, data, Some(header))?;
registry.record_volume(165, filename)?; // oops
```

The example above is problematic for two reasons: the API does not make it clear whether the written volume is Gzip encoded or not (it happens to do the latter); and the filename recorded in the registry would be wrong if we had this change of automatic extension.

With that said, it may be a good time to adopt the builder/options pattern for writing NIfTI-1 files, thus clearing ambiguities and making the library more flexible and user friendly. We'd have a `WriterOptions` type with multiple required and optional configurations such as these:

- _output file name_, as a required parameter.
- _compression_, for whether to let the library infer from the output file name or override that definition, including with a specific compression level.
- _header_ object; it was an optional argument, so it makes a good candidate for a builder parameter.

This would also be an opportunity to ground one common API for writing, regardless of their data type (RGB) or how they are represented (ndarray or a NiftiVolume type).
