### ISSUE TITLE
FSL intent

### ISSUE THREAD

**Issue by nilgoyette** [Enet4/nifti-rs#73]
I was wondering if we should add the remaining intent codes in nifti-rs, which stops at

    #define NIFTI_INTENT_SHAPE        2005

According to the standard, there are 7 others intents (`support is OPTIONAL for conforming implementations.`)

    #define NIFTI_INTENT_FSL_FNIRT_DISPLACEMENT_FIELD               2006
    #define NIFTI_INTENT_FSL_CUBIC_SPLINE_COEFFICIENTS              2007
    #define NIFTI_INTENT_FSL_DCT_COEFFICIENTS                       2008
    #define NIFTI_INTENT_FSL_QUADRATIC_SPLINE_COEFFICIENTS          2009
    #define NIFTI_INTENT_FSL_TOPUP_CUBIC_SPLINE_COEFFICIENTS        2016
    #define NIFTI_INTENT_FSL_TOPUP_QUADRATIC_SPLINE_COEFFICIENTS    2017
    #define NIFTI_INTENT_FSL_TOPUP_FIELD                            2018

I ask because of course we deal with some of those images. It made my nifti header printer crash. I don't **need** to modify nifti-rs to repair it, I'll fix it wathever happens, but I think we should add those intents because they do appear in the standard.

**Comment by Enet4** [comment]
Oh yes, somehow I had the impression that we had them all covered here. If some of them are missing, the time to add them in should be sooner than later.

> I ask because of course we deal with some of those images. It made my nifti header printer crash.

This is also unsettling, but I gather that this only happens in the writing process? The header reading process already admits invalid fields in these cases IIRC, but got writing there is some reasoning in getting unable to write an unknown or incorrect field such as this one 

So I suppose the most reasonable course of action here is to introduce the missing variants into the respective enum. Should there be a crucial need for more flexibility, we can reiterate on this. A PR would be greatly appreciated.

**Comment by nilgoyette** [comment]
No, the crash is when reading an image and it's totally my fault: `header.intent().unwrap()` will make your application crash with a FSL image :)

I'll send  a PR today.
